[workspace]
authors = [
  "The PEcAn team, A. Shiklomanov & S. Serbin"
]
channels = ["conda-forge"]
name = "serdp-rc25-4751"
# NOTE: win-64 would also be nice, but `r-rjags` is not supported on it
platforms = ["linux-64"]
version = "0.1.1"

[tasks]
[tasks.install_gh]
args = [{ arg = "pkg" }, { arg = "repo" }]
cmd = "Rscript -e 'if (!requireNamespace(\"{{ pkg }}\")) {pak::pak(\"{{ repo }}\")}'"

[tasks.install_pecan]
depends-on = [
  { task = "install_gh", args = [ { pkg = "amerifluxr" }, { repo = "chuhousen/amerifluxr" } ] },
  { task = "install_gh", args = [ { pkg = "nneo" }, { repo = "ropensci-archive/nneo" } ] }
]
cmd = "Rscript -e 'pak::repo_add(\"pecanproject.r-universe.dev\")' -e 'pak::pak(c(\"PEcAn.all\", \"PEcAn.SIPNET\", \"PEcAnAssimSequential\"))'"

[dependencies]
jags = "*"
r = ">=4"
pandoc = ">=3.9,<4"
r-roxygen2 = "==7.3.2"
r-pak = ">=0.9.2,<0.10"
"r-abind" = "*"
"r-admisc" = "*"
"r-alabama" = "*"
"r-ape" = "*"
"r-arrow" = "*"
"r-askpass" = "*"
"r-assertthat" = "*"
"r-backports" = "*"
"r-base64enc" = "*"
"r-bit" = "*"
"r-bit64" = "*"
"r-blob" = "*"
"r-brew" = "*"
"r-bridgesampling" = "*"
"r-Brobdingnag" = "*"
"r-bslib" = "*"
"r-cachem" = "*"
"r-callr" = "*"
"r-classInt" = "*"
"r-cli" = "*"
"r-clipr" = "*"
"r-clue" = "*"
"r-coda" = "*"
"r-commonmark" = "*"
"r-config" = "*"
"r-corrplot" = "*"
"r-cpp11" = "*"
"r-crayon" = "*"
"r-crosstalk" = "*"
"r-curl" = "*"
"r-data.table" = "*"
"r-DBI" = "*"
"r-dbplyr" = "*"
"r-DEoptimR" = "*"
"r-desc" = "*"
"r-devtools" = "*"
"r-DHARMa" = "*"
"r-digest" = "*"
"r-doParallel" = "*"
"r-doSNOW" = "*"
"r-dotty" = "*"
"r-dplR" = "*"
"r-dplyr" = "*"
"r-dtw" = "*"
"r-dtwclust" = "*"
"r-duckdb" = "*"
"r-e1071" = "*"
"r-ellipse" = "*"
"r-emulator" = "*"
"r-evaluate" = "*"
"r-exactextractr" = "*"
"r-expm" = "*"
"r-farver" = "*"
"r-fastmap" = "*"
"r-filelock" = "*"
"r-flexclust" = "*"
"r-fontawesome" = "*"
"r-foreach" = "*"
"r-fs" = "*"
"r-furrr" = "*"
"r-future" = "*"
"r-gap" = "*"
"r-gap.datasets" = "*"
"r-generics" = "*"
"r-geometry" = "*"
"r-getPass" = "*"
"r-ggmcmc" = "*"
"r-ggplot2" = "*"
"r-ggpubr" = "*"
"r-ggrepel" = "*"
"r-glue" = "*"
"r-gmm" = "*"
"r-gridExtra" = "*"
"r-gtable" = "*"
"r-hdf5r" = "*"
"r-here" = "*"
"r-highr" = "*"
"r-hms" = "*"
"r-htmltools" = "*"
"r-htmlwidgets" = "*"
"r-httpuv" = "*"
"r-httr" = "*"
"r-IDPmisc" = "*"
"r-isoband" = "*"
"r-iterators" = "*"
"r-itertools" = "*"
"r-jquerylib" = "*"
"r-jsonlite" = "*"
"r-jsonvalidate" = "*"
"r-keyring" = "*"
"r-knitr" = "*"
"r-labeling" = "*"
"r-later" = "*"
"r-lazyeval" = "*"
"r-lifecycle" = "*"
"r-linprog" = "*"
"r-lme4" = "*"
"r-lmtest" = "*"
"r-lpSolve" = "*"
"r-lubridate" = "*"
"r-magic" = "*"
"r-magrittr" = "*"
"r-markdown" = "*"
"r-mclust" = "*"
"r-MCMCpack" = "*"
"r-memoise" = "*"
"r-mgcv" = "*"
"r-mime" = "*"
"r-minpack.lm" = "*"
"r-minqa" = "*"
"r-mockery" = "*"
"r-modeltools" = "*"
"r-msm" = "*"
"r-mvtnorm" = "*"
"r-ncdf4" = "*"
"r-neonUtilities" = "*"
"r-nimble" = "*"
"r-nleqslv" = "*"
"r-nloptr" = "*"
"r-numbers" = "*"
"r-numDeriv" = "*"
"r-openssl" = "*"
"r-optparse" = "*"
"r-otel" = "*"
"r-parsedate" = "*"
"r-pbapply" = "*"
"r-pillar" = "*"
"r-pkgbuild" = "*"
"r-pkgconfig" = "*"
"r-pkgload" = "*"
"r-plotly" = "*"
"r-plotrix" = "*"
"r-plyr" = "*"
"r-png" = "*"
"r-polycor" = "*"
"r-prettyunits" = "*"
"r-processx" = "*"
"r-prodlim" = "*"
"r-progress" = "*"
"r-promises" = "*"
"r-proxy" = "*"
"r-ps" = "*"
"r-purrr" = "*"
"r-pwr" = "*"
"r-qgam" = "*"
"r-qrng" = "*"
"r-R.methodsS3" = "*"
"r-R.oo" = "*"
"r-R.utils" = "*"
"r-R6" = "*"
"r-randomForest" = "*"
"r-randtoolbox" = "*"
"r-rappdirs" = "*"
"r-raster" = "*"
"r-rbibutils" = "*"
"r-RColorBrewer" = "*"
"r-Rcpp" = "*"
"r-RcppArmadillo" = "*"
"r-RcppEigen" = "*"
"r-RcppParallel" = "*"
"r-RcppProgress" = "*"
"r-RcppThread" = "*"
"r-RcppTOML" = "*"
"r-rcrossref" = "*"
"r-RCurl" = "*"
"r-Rdpack" = "*"
"r-readr" = "*"
"r-reformulas" = "*"
"r-reshape" = "*"
"r-reshape2" = "*"
"r-reticulate" = "*"
"r-rgl" = "*"
"r-rjags" = "*"
"r-rjson" = "*"
"r-rlang" = "*"
"r-rlist" = "*"
"r-rmarkdown" = "*"
"r-robustbase" = "*"
"r-RPostgres" = "*"
"r-rprojroot" = "*"
"r-RSpectra" = "*"
"r-RSQLite" = "*"
"r-rstudioapi" = "*"
"r-s2" = "*"
"r-S7" = "*"
"r-sandwich" = "*"
"r-sass" = "*"
"r-scales" = "*"
"r-sessioninfo" = "*"
"r-sf" = "*"
"r-shiny" = "*"
"r-shinyjs" = "*"
"r-sourcetools" = "*"
"r-sp" = "*"
"r-spacefillr" = "*"
"r-storr" = "*"
"r-stringi" = "*"
"r-stringr" = "*"
"r-sys" = "*"
"r-tensorflow" = "*"
"r-terra" = "*"
"r-testthat" = "*"
"r-tfautograph" = "*"
"r-tfruns" = "*"
"r-tibble" = "*"
"r-tictoc" = "*"
"r-tidyr" = "*"
"r-tidyselect" = "*"
"r-tidyverse" = "*"
"r-timechange" = "*"
"r-tinytex" = "*"
"r-tmvtnorm" = "*"
"r-traits" = "*"
"r-truncnorm" = "*"
"r-tzdb" = "*"
"r-units" = "*"
"r-urltools" = "*"
"r-utf8" = "*"
"r-uuid" = "*"
"r-vctrs" = "*"
"r-vdiffr" = "*"
"r-viridisLite" = "*"
"r-vroom" = "*"
"r-webshot" = "*"
"r-whisker" = "*"
"r-withr" = "*"
"r-wk" = "*"
"r-xfun" = "*"
"r-xgboost" = "*"
"r-XML" = "*"
"r-xml2" = "*"
"r-xslt" = "*"
"r-xtable" = "*"
"r-xts" = "*"
"r-yaml" = "*"
"r-zeallot" = "*"
"r-zip" = "*"
"r-zoo" = "*"
ghostscript = ">=10.6.0,<11"
imagemagick = ">=7.1.1_47,<8"
